import pyautogui 
import pyautogui as py
import time as t 

resposta = pyautogui.confirm(
    text="Como você quer se acalmar?",
    title="Modo Calma",
    buttons=["Musica", "Respiração", "jogo fav","ver video"]
)
if resposta == "Musica":
    t.sleep(0.5)
    py.press('winleft')
    t.sleep(0.5)
    py.write("chrome")
    t.sleep(0.5)
    py.press('enter')
    t.sleep(2.0)
    py.press('f11')
    t.sleep(0.5)
    py.moveTo (858,584)
    t.sleep(0.5)
    py.click()
    t.sleep(0.5)
    py.press('f11')
    t.sleep(1.5)
    py.moveTo (681,403)
    t.sleep(2.0)
    py.click()
    t.sleep(0.5)
    py.write ('https://open.spotify.com/playlist/0r86OLVCSQ5HA6XGTb5oht', interval=0.05)
    t.sleep(1.0)
    py.press('enter')
    t.sleep(0.5)
    py.moveTo (174,480)
    t.sleep(1.0)
    py.click()
    t.sleep(4.0)
    py.click()
    t.sleep(1.0)
    py.alert('ouça e se acalme! ☻')

elif resposta == "Respiração":
    for i in range(2):
          py.alert("Inspire por 4 segundos")
          t.sleep(4)
          py.alert("Expire por 6 segundos")
          t.sleep(6)
          
        

elif resposta == "jogo fav":
     t.sleep(0.5)
     py.press('winleft')
     t.sleep(0.5)
     py.write("roblox player")
     t.sleep(0.5)
     py.press('enter')
     t.sleep(0.5)
     py.alert('escolha seu jogo de conforto e se divirta - se ☻')
     t.sleep(5)
elif resposta == "ver video":
     resposta = pyautogui.confirm(
    text="aonde desejar ver video?",
    title="atenção!",
    buttons=["youtube", "instagram realls", "tiktok"
    "",]
     )
     if resposta == "youtube":
        t.sleep(0.5)
        py.press('winleft')
        t.sleep(0.5)
        py.write("chrome")
        t.sleep(0.5)
        py.press('enter')
        t.sleep(2.0)
        py.press('f11')
        t.sleep(0.5)
        py.moveTo (858,584)
        t.sleep(0.5)
        py.click()
        t.sleep(0.5)
        py.press('f11')
        t.sleep(1.5)
        py.moveTo (681,403)
        t.sleep(2.0)
        py.click()
        t.sleep(0.5)
        py.write ('https://www.youtube.com.br', interval=0.05)
        t.sleep(1.0)
        py.press('enter')
        t.sleep(0.5)
        py.alert('escolha seu video de conforto e se divirta!')
     elif resposta == 'instagram realls':    
        t.sleep(0.5)
        py.press('winleft')
        t.sleep(0.5)
        py.write("chrome")
        t.sleep(0.5)
        py.press('enter')
        t.sleep(2.0)
        py.press('f11')
        t.sleep(0.5)
        py.moveTo (858,584)
        t.sleep(0.5)
        py.click()
        t.sleep(0.5)
        py.press('f11')
        t.sleep(1.5)
        py.moveTo (681,403)
        t.sleep(2.0)
        py.click()
        t.sleep(0.5)
        py.write ('https://www.instagram.com/', interval=0.05)
        t.sleep(1.0)
        py.press('enter')
        t.sleep(0.5) 
        py.moveTo (93,343)
        t.sleep(1.0)
        py.click()
        t.sleep(1.0) 
        py.alert("assiste os melhores videos")

     elif resposta == 'tiktok':    
        t.sleep(0.5)
        py.press('winleft')
        t.sleep(0.5)
        py.write("chrome")
        t.sleep(0.5)
        py.press('enter')
        t.sleep(2.0)
        py.press('f11')
        t.sleep(0.5)
        py.moveTo (858,584)
        t.sleep(0.5)
        py.click()
        t.sleep(0.5)
        py.press('f11')
        t.sleep(1.5)
        py.moveTo (681,403)
        t.sleep(2.0)
        py.click()
        t.sleep(0.5)
        py.write ('https://www.tiktok.com/pt-BR/', interval=0.05)
        t.sleep(1.0)
        py.press('enter')
        t.sleep(0.5) 